In [487]:
import pandas as pd
import numpy as np

# Data Load

In [488]:
data = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
df = pd.read_csv(data)

In [489]:
df

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

# Data Preprocessing

In [490]:
x = df.iloc[:,0:13]
y = df.iloc[:, -1]

In [491]:
x.columns

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat'],
      dtype='object')

In [492]:
x["intercept"]=1
x = x[x.columns[::-1]]
del x['chas']

In [493]:
x

intercept  lstat       b  ptratio  tax  rad     dis   age     rm    nox  \
0            1   4.98  396.90     15.3  296    1  4.0900  65.2  6.575  0.538   
1            1   9.14  396.90     17.8  242    2  4.9671  78.9  6.421  0.469   
2            1   4.03  392.83     17.8  242    2  4.9671  61.1  7.185  0.469   
3            1   2.94  394.63     18.7  222    3  6.0622  45.8  6.998  0.458   
4            1   5.33  396.90     18.7  222    3  6.0622  54.2  7.147  0.458   
..         ...    ...     ...      ...  ...  ...     ...   ...    ...    ...   
501          1   9.67  391.99     21.0  273    1  2.4786  69.1  6.593  0.573   
502          1   9.08  396.90     21.0  273    1  2.2875  76.7  6.120  0.573   
503          1   5.64  396.90     21.0  273    1  2.1675  91.0  6.976  0.573   
504          1   6.48  393.45     21.0  273    1  2.3889  89.3  6.794  0.573   
505          1   7.88  396.90     21.0  273    1  2.5050  80.8  6.030  0.573   

     indus    zn     crim  
0     2.31  18.0  0.00632  
1     7.07   0.0  0.02731  
2     7.07   0.0  0.02729  
3     2.18   0.0  0.03237  
4     2.18   0.0  0.06905  
..     ...   ...      ...  
501  11.93   0.0  0.06263  
502  11.93   0.0  0.04527  
503  11.93   0.0  0.06076  
504  11.93   0.0  0.10959  
505  11.93   0.0  0.04741  

[506 rows x 13 columns]

In [494]:
xx = x.to_numpy()

# QR Decomposition

In [495]:
Q = []
a = xx.copy()
for i in range(np.shape(a)[1]):
    s = a[:,i]
    for j in range(i):
        s -= (np.dot(a[:,i],a[:,j])/np.sum(a[:,j]*a[:,j]))*a[:,j]
    Q.append(s/np.sqrt(np.sum(s*s)))
Q = np.transpose(Q)

Q = []

ss = []

R = np.zeros(shape=(13,13))

a = xx.copy()

for i in range(np.shape(a)[1]):

    s = a[:,i]
    
    for j in range(i):
    
        aa = np.dot(a[:,i],a[:,j])/np.sqrt(np.dot(a[:,j]*a[:,j]))
        
        bb = np.sqrt(np.dot(a[:,j]*a[:,j]))/a[:,j]
        
        s -= aa*bb
        
    ss.append(aa)
    
    Q.append(s/np.sqrt(np.sum(s*s)))
    
Q = np.transpose(Q)

aa = np.dot(a[:,i],a[:,j])/np.sqrt(np.dot(a[:,j]*a[:,j]))

bb = np.sqrt(np.dot(a[:,j]*a[:,j]))/a[:,j]

In [496]:
Q

array([[ 0.04445542, -0.04781458,  0.00225973, ..., -0.08079514,
        -0.01595605,  0.01477565],
       [ 0.04445542, -0.0218916 ,  0.01245773, ...,  0.01058817,
        -0.04178724,  0.01278396],
       [ 0.04445542, -0.05373449, -0.00220095, ...,  0.02172806,
        -0.05453185,  0.02293818],
       ...,
       [ 0.04445542, -0.0437018 ,  0.00387768, ..., -0.00136004,
         0.03502232,  0.01955675],
       [ 0.04445542, -0.03846735,  0.00412983, ..., -0.00115583,
         0.03267378,  0.01889789],
       [ 0.04445542, -0.02974327,  0.00936891, ..., -0.00736816,
         0.03730555,  0.01507722]])

In [497]:
R = np.zeros(shape=(13,13))
for i in range(np.shape(a)[1]):
    for j in range(i+1):
        R_temp = np.dot(Q[:,j],xx[:,i])
        R[j,i] = R_temp

In [498]:
A = Q@R

In [499]:
pd.DataFrame(A)

0     1       2     3      4    5       6     7      8      9      10  \
0    1.0  4.98  396.90  15.3  296.0  1.0  4.0900  65.2  6.575  0.538   2.31   
1    1.0  9.14  396.90  17.8  242.0  2.0  4.9671  78.9  6.421  0.469   7.07   
2    1.0  4.03  392.83  17.8  242.0  2.0  4.9671  61.1  7.185  0.469   7.07   
3    1.0  2.94  394.63  18.7  222.0  3.0  6.0622  45.8  6.998  0.458   2.18   
4    1.0  5.33  396.90  18.7  222.0  3.0  6.0622  54.2  7.147  0.458   2.18   
..   ...   ...     ...   ...    ...  ...     ...   ...    ...    ...    ...   
501  1.0  9.67  391.99  21.0  273.0  1.0  2.4786  69.1  6.593  0.573  11.93   
502  1.0  9.08  396.90  21.0  273.0  1.0  2.2875  76.7  6.120  0.573  11.93   
503  1.0  5.64  396.90  21.0  273.0  1.0  2.1675  91.0  6.976  0.573  11.93   
504  1.0  6.48  393.45  21.0  273.0  1.0  2.3889  89.3  6.794  0.573  11.93   
505  1.0  7.88  396.90  21.0  273.0  1.0  2.5050  80.8  6.030  0.573  11.93   

               11       12  
0    1.800000e+01  0.00632  
1   -6.737939e-15  0.02731  
2    4.119100e-14  0.02729  
3    3.136188e-14  0.03237  
4    3.786622e-14  0.06905  
..            ...      ...  
501  1.253383e-13  0.06263  
502  7.751398e-14  0.04527  
503  1.463155e-13  0.06076  
504  1.327832e-13  0.10959  
505  6.695400e-14  0.04741  

[506 rows x 13 columns]

In [500]:
x

intercept  lstat       b  ptratio  tax  rad     dis   age     rm    nox  \
0            1   4.98  396.90     15.3  296    1  4.0900  65.2  6.575  0.538   
1            1   9.14  396.90     17.8  242    2  4.9671  78.9  6.421  0.469   
2            1   4.03  392.83     17.8  242    2  4.9671  61.1  7.185  0.469   
3            1   2.94  394.63     18.7  222    3  6.0622  45.8  6.998  0.458   
4            1   5.33  396.90     18.7  222    3  6.0622  54.2  7.147  0.458   
..         ...    ...     ...      ...  ...  ...     ...   ...    ...    ...   
501          1   9.67  391.99     21.0  273    1  2.4786  69.1  6.593  0.573   
502          1   9.08  396.90     21.0  273    1  2.2875  76.7  6.120  0.573   
503          1   5.64  396.90     21.0  273    1  2.1675  91.0  6.976  0.573   
504          1   6.48  393.45     21.0  273    1  2.3889  89.3  6.794  0.573   
505          1   7.88  396.90     21.0  273    1  2.5050  80.8  6.030  0.573   

     indus    zn     crim  
0     2.31  18.0  0.00632  
1     7.07   0.0  0.02731  
2     7.07   0.0  0.02729  
3     2.18   0.0  0.03237  
4     2.18   0.0  0.06905  
..     ...   ...      ...  
501  11.93   0.0  0.06263  
502  11.93   0.0  0.04527  
503  11.93   0.0  0.06076  
504  11.93   0.0  0.10959  
505  11.93   0.0  0.04741  

[506 rows x 13 columns]

# Least Square Method

In [501]:
Y = np.transpose(Q)@y

In [502]:
beta = np.zeros(np.shape(Y))

for i in range(13-1, -1, -1):
    tmp = Y[i]
    for j in range(13-1, i, -1):
        tmp -= beta[j]*R[i,j]
        
    beta[i] = tmp/R[i,i]

In [503]:
beta

array([ 3.68919598e+01, -5.34157620e-01,  9.74145094e-03, -9.90958031e-01,
       -1.37558288e-02,  3.28311011e-01, -1.48537390e+00,  2.78375651e-03,
        3.85049169e+00, -1.73669994e+01,  4.03114536e-02,  4.70524578e-02,
       -1.13139078e-01])

# Comparison

In [504]:
from sklearn.linear_model import LinearRegression
mlr = LinearRegression(fit_intercept=False)
mlr.fit(x, y) 

LinearRegression(fit_intercept=False)

In [505]:
print("계수: ", mlr.coef_)

계수:  [ 3.68919598e+01 -5.34157620e-01  9.74145094e-03 -9.90958031e-01
 -1.37558288e-02  3.28311011e-01 -1.48537390e+00  2.78375651e-03
  3.85049169e+00 -1.73669994e+01  4.03114536e-02  4.70524578e-02
 -1.13139078e-01]


# Inverse of R

In [506]:
iden = np.identity(n=13)

In [507]:
inv_R=np.zeros(shape=(13,13))

In [508]:
for i in range(12,-1,-1):
    for j in range(12,-1,-1):
        inv_R[j,i] = (iden[i,j]-np.sum(R[j]*inv_R[:,i]))/R[j,j]

In [509]:
np.matrix.round(inv_R@R,1)

array([[ 1.,  0., -0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0., -0.,  0.],
       [ 0.,  1., -0., -0., -0., -0.,  0.,  0., -0.,  0., -0., -0., -0.],
       [ 0.,  0.,  1., -0., -0.,  0.,  0., -0.,  0.,  0., -0.,  0.,  0.],
       [ 0.,  0.,  0.,  1., -0., -0.,  0., -0.,  0., -0., -0.,  0., -0.],
       [ 0.,  0.,  0.,  0.,  1., -0., -0., -0., -0., -0., -0.,  0., -0.],
       [ 0.,  0.,  0.,  0.,  0.,  1., -0.,  0.,  0.,  0.,  0., -0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0., -0.,  0., -0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0., -0., -0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1., -0.,  0., -0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1., -0., -0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1., -0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1., -0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

# Standard Error of $\hat{\beta}$ and p-value

In [510]:
y_hat = xx@beta
mse = np.sum((y_hat-y)**2)/(506-13)
variance_of_beta_hat = (inv_R@np.transpose(inv_R))*mse
se = np.sqrt(np.diag(variance_of_beta_hat))

In [511]:
se

array([5.14651577e+00, 5.10716097e-02, 2.70605738e-03, 1.31399092e-01,
       3.76569995e-03, 6.65423349e-02, 2.01186792e-01, 1.33089635e-02,
       4.21402010e-01, 3.85122412e+00, 6.17074446e-02, 1.38468825e-02,
       3.31129893e-02])

In [512]:
from scipy.stats import t
p_val=[]
for i in range(13):
    p_temp = 2*(1- t.cdf(abs(mlr.coef_[i]/se[i]), 506-13))
    p_val.append(round(float(p_temp),3))

In [513]:
p_val

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.834, 0.0, 0.0, 0.514, 0.001, 0.001]

# Summary Table

In [514]:
table= pd.DataFrame()

In [515]:
table['Variable'] = x.columns
table['coef'] = mlr.coef_
table['S.E']= se
table['p-value'] = p_val
table.loc[(table['p-value'] < 0.05) & (table['p-value'] >= 0.01), 'star'] = '*'  
table.loc[(table['p-value'] < 0.01) & (table['p-value'] >= 0.001), 'star'] = '**' 
table.loc[(table['p-value'] < 0.001), 'star'] = '***' 

In [516]:
table

Variable       coef       S.E  p-value star
0   intercept  36.891960  5.146516    0.000  ***
1       lstat  -0.534158  0.051072    0.000  ***
2           b   0.009741  0.002706    0.000  ***
3     ptratio  -0.990958  0.131399    0.000  ***
4         tax  -0.013756  0.003766    0.000  ***
5         rad   0.328311  0.066542    0.000  ***
6         dis  -1.485374  0.201187    0.000  ***
7         age   0.002784  0.013309    0.834  NaN
8          rm   3.850492  0.421402    0.000  ***
9         nox -17.366999  3.851224    0.000  ***
10      indus   0.040311  0.061707    0.514  NaN
11         zn   0.047052  0.013847    0.001   **
12       crim  -0.113139  0.033113    0.001   **

In [517]:
from statsmodels.formula.api import ols
df_ols = df.copy()
df_ols['intercept'] = 1
df_ols

model = ols("medv~lstat+b+ptratio+tax+rad+dis+age+rm+nox+indus+zn+crim",data=df_ols).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                   medv   R-squared:                       0.736
Model:                            OLS   Adj. R-squared:                  0.729
Method:                 Least Squares   F-statistic:                     114.3
Date:                Fri, 18 Mar 2022   Prob (F-statistic):          7.30e-134
Time:                        15:51:20   Log-Likelihood:                -1503.8
No. Observations:                 506   AIC:                             3034.
Df Residuals:                     493   BIC:                             3088.
Df Model:                          12                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     36.8920      5.147      7.168      0.000      26.780      47.004
lstat         -0.5342      0.051    -10.459      0.000      -0.635      -0.434
b              0.0097      0.003      3.600      0.000       0.004       0.015
ptratio       -0.9910      0.131     -7.542      0.000      -1.249      -0.733
tax           -0.0138      0.004     -3.653      0.000      -0.021      -0.006
rad            0.3283      0.067      4.934      0.000       0.198       0.459
dis           -1.4854      0.201     -7.383      0.000      -1.881      -1.090
age            0.0028      0.013      0.209      0.834      -0.023       0.029
rm             3.8505      0.421      9.137      0.000       3.023       4.678
nox          -17.3670      3.851     -4.509      0.000     -24.934      -9.800
indus          0.0403      0.062      0.653      0.514      -0.081       0.162
zn             0.0471      0.014      3.398      0.001       0.020       0.074
crim          -0.1131      0.033     -3.417      0.001      -0.178      -0.048
==============================================================================
Omnibus:                      190.856   Durbin-Watson:                   1.016
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              898.352
Skew:                           1.619   Prob(JB):                    8.42e-196
Kurtosis:                       8.668   Cond. No.                     1.51e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.51e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""